/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.calculator;

import javax.swing.JOptionPane;
import java.text.DecimalFormat;
/**
 *
 * @author Afifah Bazli
 */
public class vendingMachine extends javax.swing.JFrame {

    /**
     * Creates new form vendingMachine
     */
    public vendingMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cokeRB = new javax.swing.JRadioButton();
        spriteRB = new javax.swing.JRadioButton();
        mugRB = new javax.swing.JRadioButton();
        mountaindewRB = new javax.swing.JRadioButton();
        strawberryRB = new javax.swing.JRadioButton();
        purchaseButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        labelInsert = new javax.swing.JLabel();
        labelChange = new javax.swing.JLabel();
        oneringgitField = new javax.swing.JTextField();
        changeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fiftysenField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        twentysenField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tensenField = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine");
        setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel1.setText("Vending Machine");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select an item"));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        cokeRB.setText("Coca- Cola = RM2.00");
        cokeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeRBActionPerformed(evt);
            }
        });

        spriteRB.setText("Sprite = RM 1.80");
        spriteRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteRBActionPerformed(evt);
            }
        });

        mugRB.setText("MUG = RM1.60");
        mugRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mugRBActionPerformed(evt);
            }
        });

        mountaindewRB.setText("Mountain Dew = RM 1.80");
        mountaindewRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mountaindewRBActionPerformed(evt);
            }
        });

        strawberryRB.setText("F&N Strawberry = RM 2.30");
        strawberryRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spriteRB)
                    .addComponent(cokeRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mountaindewRB)
                    .addComponent(mugRB))
                .addGap(27, 27, 27)
                .addComponent(strawberryRB)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeRB)
                    .addComponent(mugRB)
                    .addComponent(strawberryRB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spriteRB)
                    .addComponent(mountaindewRB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        purchaseButton.setBackground(new java.awt.Color(0, 204, 51));
        purchaseButton.setText("Purchase");
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(204, 204, 255));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        labelInsert.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelInsert.setText("Insert Money   :");

        labelChange.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelChange.setText("Change (RM):");

        oneringgitField.setText("0");

        changeField.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("RM 1.00 :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("RM 0.50 :");

        fiftysenField.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("RM 0.20 :");

        twentysenField.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("RM 0.10 :");

        tensenField.setText("0");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(purchaseButton)
                                .addGap(68, 68, 68)
                                .addComponent(clearButton)
                                .addGap(69, 69, 69)
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBack))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelChange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tensenField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(twentysenField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fiftysenField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oneringgitField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(labelInsert)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(labelInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneringgitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fiftysenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(twentysenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tensenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseButton)
                    .addComponent(clearButton)
                    .addComponent(cancelButton)
                    .addComponent(jButtonBack))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mountaindewRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mountaindewRBActionPerformed
        // only select one
         if(mountaindewRB.isSelected()){
            spriteRB.setSelected(false);
            mugRB.setSelected(false);
            cokeRB.setSelected(false);
            strawberryRB.setSelected(false);
         //   plusRB.setSelected(false);
        }
    }//GEN-LAST:event_mountaindewRBActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      // cancel selection
      System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // clear all selection
        cokeRB.setSelected(false);
        spriteRB.setSelected(false);
        mugRB.setSelected(false);
        mountaindewRB.setSelected(false);
        strawberryRB.setSelected(false);
        //plusRB.setSelected(false);
        oneringgitField.setText("0");
        fiftysenField.setText("0");
        twentysenField.setText("0");
        tensenField.setText("0");
        changeField.setText(" ");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void cokeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeRBActionPerformed
        // changing button to select only one
        if(cokeRB.isSelected()){
            spriteRB.setSelected(false);
            mugRB.setSelected(false);
            mountaindewRB.setSelected(false);
            strawberryRB.setSelected(false);
           // plusRB.setSelected(false);
        }
    }//GEN-LAST:event_cokeRBActionPerformed

    private void spriteRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteRBActionPerformed
       // change to only select one 
        if(spriteRB.isSelected()){
            cokeRB.setSelected(false);
            mugRB.setSelected(false);
            mountaindewRB.setSelected(false);
            strawberryRB.setSelected(false);
         //   plusRB.setSelected(false);
        }
    }//GEN-LAST:event_spriteRBActionPerformed

    private void mugRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mugRBActionPerformed
        // change only slect one
         if(mugRB.isSelected()){
            spriteRB.setSelected(false);
            cokeRB.setSelected(false);
            mountaindewRB.setSelected(false);
            strawberryRB.setSelected(false);
          //  plusRB.setSelected(false);
        }
    }//GEN-LAST:event_mugRBActionPerformed

    private void strawberryRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryRBActionPerformed
        // change to select one
         if(strawberryRB.isSelected()){
            spriteRB.setSelected(false);
            mugRB.setSelected(false);
            mountaindewRB.setSelected(false);
            cokeRB.setSelected(false);
            //plusRB.setSelected(false);
        }
    }//GEN-LAST:event_strawberryRBActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        // insert money if enough money
        DecimalFormat commaFormat = new DecimalFormat("##.##");
        
        double money = 0.0;
        double balance = 0.0;
        
        money = (1.0 * Double.parseDouble(oneringgitField.getText())) + (0.5 * Double.parseDouble(fiftysenField.getText())) +
                (0.2 * Double.parseDouble(twentysenField.getText())) + (0.1 * Double.parseDouble(tensenField.getText()));

         //totalField.setText(String.valueOf(money));
         
        if(cokeRB.isSelected()){
            balance = money-2.00;
        }else if(spriteRB.isSelected()){
             balance = money-1.80;
         }else if(mugRB.isSelected()){
             balance = money-1.60;   
         }else if(mountaindewRB.isSelected()){
             balance = money-1.80;
         }else if(strawberryRB.isSelected()){
            balance = money-2.30;
        // }else if(plusRB.isSelected()){
             //balance = money-1.50;
        }
        
        if(money < 0){
            JOptionPane.showMessageDialog(rootPane, "Sorry you do not have enough money");
        }else{
            changeField.setText(Double.toString(balance));
        }
        
        
          
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendingMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField changeField;
    private javax.swing.JButton clearButton;
    private javax.swing.JRadioButton cokeRB;
    private javax.swing.JTextField fiftysenField;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelChange;
    private javax.swing.JLabel labelInsert;
    private javax.swing.JRadioButton mountaindewRB;
    private javax.swing.JRadioButton mugRB;
    private javax.swing.JTextField oneringgitField;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JRadioButton spriteRB;
    private javax.swing.JRadioButton strawberryRB;
    private javax.swing.JTextField tensenField;
    private javax.swing.JTextField twentysenField;
    // End of variables declaration//GEN-END:variables
}
